#!/bin/sh

# This assumes that dr-jni is a sibling directory to dr-android-tools inside a dragonruby directory.
cd $(dirname $0)/..

./dr-android-tools/build-cext ./dr-jni/jni.c dr-jni/test-game
./dr-android-tools/build-and-test-on-device dr-jni/test-game
